/**
 * Shell completion scripts, derived from the citty tree.
 *
 * Derived rather than hand-written for the usual reason: a hand-written
 * completion is a second description of the command surface, and it goes stale
 * on the first command anyone adds. Here the tree is walked at generation time,
 * so the emitted script names exactly the commands that exist.
 *
 * The three shells get genuinely different scripts — bash's `complete -F`,
 * zsh's `_describe`, and fish's per-command `-n` conditions have no useful
 * common shape, and pretending otherwise produces three broken scripts instead
 * of one.
 */
import { CliError } from '../errors.js'
import { type TreeNode, walkCommands } from './command-tree.js'

export const SUPPORTED_SHELLS = ['bash', 'zsh', 'fish'] as const
export type Shell = (typeof SUPPORTED_SHELLS)[number]

export function assertShell(value: string): Shell {
  if ((SUPPORTED_SHELLS as readonly string[]).includes(value)) return value as Shell
  throw new CliError(`Unsupported shell: "${value}". Supported: ${SUPPORTED_SHELLS.join(', ')}`, {
    type: 'validation',
    subtype: 'unsupported_shell',
    hint: 'a2wave completion bash',
  })
}

interface Entry {
  path: string
  description: string
  flags: string[]
}

function collect(root: TreeNode): Entry[] {
  return walkCommands(root).map((e) => ({
    path: e.path,
    description: e.node.meta?.description ?? '',
    flags: Object.entries(e.node.args ?? {})
      .filter(([, spec]) => spec.type !== 'positional')
      .map(([name]) => `--${name}`),
  }))
}

/** Single-quote for a shell literal by doubling out any embedded quote. */
function shq(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function bash(entries: Entry[]): string {
  // One flat lookup table keyed by the space-joined path. bash has no nested
  // structure worth using here, and the table stays readable when a user pipes
  // the script to a file and reads it.
  const cases = entries
    .map((e) => `    ${shq(e.path)}) echo ${shq([...e.flags].join(' '))} ;;`)
    .join('\n')
  const roots = [...new Set(entries.map((e) => e.path.split(' ')[0]))].join(' ')
  const children = [...new Set(entries.filter((e) => e.path.includes(' ')).map((e) => e.path))]

  return `# a2wave bash completion — generated by \`a2wave completion bash\`
# Install: a2wave completion bash > /etc/bash_completion.d/a2wave

_a2wave_flags() {
  case "$1" in
${cases}
  esac
}

_a2wave_children() {
  local prefix="$1"
  local all=${shq(children.join('\n'))}
  echo "$all" | while IFS= read -r line; do
    case "$line" in
      "$prefix "*) echo "${'${line#"$prefix "}'}" | cut -d' ' -f1 ;;
    esac
  done | sort -u
}

_a2wave() {
  local cur words path
  cur="${'${COMP_WORDS[COMP_CWORD]}'}"
  words=("${'${COMP_WORDS[@]:1:$COMP_CWORD-1}'}")
  path=""
  for w in "${'${words[@]}'}"; do
    case "$w" in -*) continue ;; esac
    path="${'${path:+$path }'}$w"
  done

  if [ -z "$path" ]; then
    COMPREPLY=($(compgen -W ${shq(roots)} -- "$cur"))
    return
  fi

  local subs flags
  subs="$(_a2wave_children "$path")"
  flags="$(_a2wave_flags "$path")"
  COMPREPLY=($(compgen -W "$subs $flags" -- "$cur"))
}

complete -F _a2wave a2wave
`
}

function zsh(entries: Entry[]): string {
  // zsh gets descriptions, which is most of why anyone installs a completion.
  const lines = entries
    .map((e) => `  ${shq(`${e.path.replace(/ /g, ':')}`)}:${shq(e.description)}`)
    .join('\n')
  const specs = entries
    .map((e) => `    ${shq(e.path)}) _values 'flag' ${e.flags.map(shq).join(' ')} ;;`)
    .join('\n')

  return `#compdef a2wave
# a2wave zsh completion — generated by \`a2wave completion zsh\`
# Install: a2wave completion zsh > "${'${fpath[1]}'}/_a2wave"

_a2wave_paths=(
${lines}
)

_a2wave() {
  local path="" w
  for w in ${'${words[2,CURRENT-1]}'}; do
    [[ "$w" == -* ]] && continue
    path="${'${path:+$path }'}$w"
  done

  local -a subs
  local entry
  for entry in $_a2wave_paths; do
    local p="${'${${entry%%:*}//:/ }'}"
    if [[ -z "$path" && "$p" != *" "* ]]; then
      subs+=("$p")
    elif [[ -n "$path" && "$p" == "$path "* ]]; then
      subs+=("${'${${p#$path }%% *}'}")
    fi
  done

  if (( ${'${#subs}'} )); then
    _describe 'command' subs
  fi

  case "$path" in
${specs}
  esac
}

_a2wave "$@"
`
}

function fish(entries: Entry[]): string {
  // fish keys every rule on the already-typed words, so each command and each
  // flag is one independent line — no dispatcher to keep in sync.
  const lines: string[] = [
    '# a2wave fish completion — generated by `a2wave completion fish`',
    '# Install: a2wave completion fish > ~/.config/fish/completions/a2wave.fish',
    '',
    'function __a2wave_path',
    '  set -l tokens (commandline -opc)',
    '  set -l parts',
    '  for t in $tokens[2..-1]',
    '    string match -q -- "-*" $t; and continue',
    '    set -a parts $t',
    '  end',
    '  string join " " $parts',
    'end',
    '',
  ]

  for (const entry of entries) {
    const segments = entry.path.split(' ')
    const leafName = segments[segments.length - 1]
    const parent = segments.slice(0, -1).join(' ')
    const condition = parent ? `test (__a2wave_path) = ${shq(parent)}` : 'test -z (__a2wave_path)'
    lines.push(
      `complete -c a2wave -f -n ${shq(condition)} -a ${shq(leafName)} -d ${shq(entry.description)}`,
    )
    for (const flag of entry.flags) {
      lines.push(
        `complete -c a2wave -f -n ${shq(`test (__a2wave_path) = ${entry.path}`)} -l ${shq(flag.slice(2))}`,
      )
    }
  }

  return `${lines.join('\n')}\n`
}

export function buildCompletion(root: TreeNode, shell: Shell): string {
  const entries = collect(root)
  if (shell === 'bash') return bash(entries)
  if (shell === 'zsh') return zsh(entries)
  return fish(entries)
}
