import { randomBytes } from 'node:crypto'

export const DEFAULT_PORT = 3502

/** 64-char hex string for AUTH_SECRET (matches `openssl rand -hex 32`). */
export function generateAuthSecret(): string {
  return randomBytes(32).toString('hex')
}

/**
 * Password for the bundled postgres sidecar. Hex only: the same value is
 * embedded verbatim in DATABASE_URL's userinfo, so any character that needs
 * percent-encoding would make the two .env keys disagree.
 */
export function generatePostgresPassword(): string {
  return randomBytes(16).toString('hex')
}

/**
 * Reject a --database-url that is not a PostgreSQL URL.
 *
 * The scheme alone selects the backend server-side; anything else is treated
 * as a SQLite file path, and a HOST path is meaningless inside the container —
 * the flag exists for external databases only. Whitespace is checked before
 * URL parsing because `new URL()` silently STRIPS tabs and newlines: parsing
 * alone would accept an injection payload and then write a different string
 * into .env (where a newline starts a new env line).
 */
export function validateDatabaseUrl(url: string): void {
  if (/[\s\p{Cc}]/u.test(url)) {
    throw new Error('Invalid --database-url: whitespace and control characters are not allowed.')
  }
  // The value is written unquoted into .env, whose values Compose interpolates:
  // a literal `$` in a password silently becomes a variable expansion and the
  // connection fails with a wrong-password error that never names the cause.
  // Escaping as `$$` would gamble on two consumption paths (interpolation and
  // env_file) agreeing across Compose versions; the URL's own escape does not.
  if (url.includes('$')) {
    throw new Error(
      'Invalid --database-url: a literal $ would be mangled by docker compose variable interpolation. Percent-encode it as %24.',
    )
  }
  let parsed: URL
  try {
    parsed = new URL(url)
  } catch {
    throw new Error(
      `Invalid --database-url: ${JSON.stringify(url)} is not a URL. Expected postgres://user:password@host:5432/dbname`,
    )
  }
  if (parsed.protocol !== 'postgres:' && parsed.protocol !== 'postgresql:') {
    throw new Error(
      `Invalid --database-url: only postgres:// (or postgresql://) URLs are supported, got ${JSON.stringify(url)}. SQLite needs no flag — it is the default.`,
    )
  }
}

/**
 * Unique, stable Compose project name persisted per install. Without it,
 * Compose defaults the project name to the directory BASENAME — /srv/a/a2wave
 * and /srv/b/a2wave would resolve to the same `a2wave_a2wave-data` volume,
 * the second install would mount the first one's database, and either side's
 * `setup --down` (compose down -v) would delete the shared volume.
 */
export function generateProjectName(): string {
  return `a2wave-${randomBytes(4).toString('hex')}`
}

// Docker image reference charset (name[:tag][@digest]). Anything outside this
// (newlines, spaces, quotes, '#') could inject extra compose directives when
// interpolated into the generated YAML.
const IMAGE_REF_PATTERN = /^[a-z0-9]+(?:[._\-/:][a-zA-Z0-9._-]+)*(?:@sha256:[a-f0-9]+)?$/

/** Reject image refs that are not a plain docker reference (YAML-injection guard). */
export function validateImageRef(ref: string): void {
  if (!IMAGE_REF_PATTERN.test(ref)) {
    throw new Error(
      `Invalid image reference: ${JSON.stringify(ref)}. Expected a plain docker image ref like ghcr.io/org/name:tag`,
    )
  }
}

export interface EnvFileInput {
  authSecret: string
  port: number
  /** External base URL of the instance, e.g. http://localhost:3502 */
  baseUrl: string
  /** Unique Compose project name (see generateProjectName) */
  projectName: string
  /** Container image; drives A2WAVE_IMAGE, which `setup --upgrade` rewrites. */
  image?: string
  /** PostgreSQL URL (external or sidecar-derived); omitted means SQLite. */
  databaseUrl?: string
  /** Password of the bundled postgres sidecar; only set with --with-postgres. */
  postgresPassword?: string
}

/**
 * Render the generated .env content for a fresh install.
 * Deliberately no ADMIN_PASSWORD: the admin password is set on first login via
 * the web setup screen or `a2wave setup` interactive prompt (POST /auth/setup),
 * so it never lands in a file or terminal scrollback.
 */
export function buildEnvFile(input: EnvFileInput): string {
  const lines = [
    '# Generated by `a2wave setup` — edit and `docker compose up -d` to apply.',
    '',
    '# Unique Compose project name. DO NOT change or remove: without it Compose',
    '# falls back to the directory basename, and two installs in same-named',
    '# directories would share (and on teardown, delete) the same data volume.',
    `COMPOSE_PROJECT_NAME=${input.projectName}`,
    '',
    '# Auth signing secret (keep private; rotating it invalidates all sessions)',
    `AUTH_SECRET=${input.authSecret}`,
    '',
    '# Host port the platform is exposed on',
    `A2WAVE_PORT=${input.port}`,
    '',
    '# Container image. `a2wave setup --upgrade` rewrites this line; changing it',
    '# by hand and running `docker compose up -d` has the same effect.',
    `A2WAVE_IMAGE=${input.image ?? ''}`,
    '',
    '# Browser origin allowed to call the API',
    `CORS_ORIGIN=${input.baseUrl}`,
  ]
  if (input.databaseUrl) {
    lines.push(
      '',
      '# Database backend. A postgres:// URL selects PostgreSQL — EXPERIMENTAL:',
      '# no production soak time yet, and there is NO SQLite -> PostgreSQL data',
      '# migration path. Remove the key to fall back to SQLite in the data volume.',
      `DATABASE_URL=${input.databaseUrl}`,
    )
  }
  if (input.postgresPassword) {
    lines.push(
      '',
      '# Password of the bundled postgres sidecar (also embedded in DATABASE_URL',
      '# above — keep the two in sync when rotating it).',
      `POSTGRES_PASSWORD=${input.postgresPassword}`,
    )
  }
  // Gateway signing only reaches its standards path (URL issuer + discovery)
  // over https, so only prefill the origin when the install is already https;
  // an http value would be accepted by env validation but rejected as an issuer.
  if (input.baseUrl.startsWith('https://')) {
    lines.push(
      '',
      '# External origin of this instance. Lets JWT-verifying gateways discover',
      '# the public key at /.well-known/jwks.json instead of being handed it.',
      `PUBLIC_URL=${input.baseUrl}`,
    )
  }
  if (input.baseUrl.startsWith('http://')) {
    lines.push(
      '',
      '# HTTP deployment: secure cookies would be dropped by the browser and',
      '# login would loop back to the login page. Set true once behind HTTPS.',
      'AUTH_COOKIE_SECURE=false',
    )
  }
  lines.push('')
  return lines.join('\n')
}

/**
 * Read the `A2WAVE_IMAGE` value from an install's .env, or null when absent.
 *
 * The image is a plain env key rather than a line inside docker-compose.yml
 * precisely so that reading and writing it needs no YAML understanding.
 */
export function readEnvImage(env: string): string | null {
  const raw = env.match(/^A2WAVE_IMAGE=(.*)$/m)?.[1]?.trim()
  if (!raw) return null
  // Strip surrounding quotes: a hand-written `A2WAVE_IMAGE="a2wave:1.0"` is a
  // valid env value, but keeping the quotes would surface a ref the operator
  // cannot paste into a docker command in the rollback messages.
  const unquoted = raw.replace(/^(['"])(.*)\1$/, '$2')
  return unquoted ? unquoted : null
}

/**
 * Read the `DATABASE_URL` value from an install's .env, or null when absent.
 * Used by `setup --upgrade` to warn that the data-volume backup does not cover
 * a PostgreSQL backend's data.
 */
export function readEnvDatabaseUrl(env: string): string | null {
  const raw = env.match(/^DATABASE_URL=(.*)$/m)?.[1]?.trim()
  if (!raw) return null
  const unquoted = raw.replace(/^(['"])(.*)\1$/, '$2')
  return unquoted ? unquoted : null
}

/**
 * Return `env` with `A2WAVE_IMAGE` set to `image`, appending the key when it is
 * absent (an install predating the key) and leaving every other byte untouched.
 *
 * Only that one line may move: a regenerated AUTH_SECRET invalidates every
 * session, and a regenerated COMPOSE_PROJECT_NAME points Compose at a different
 * volume and orphans the database while still reporting success.
 */
export function replaceEnvImage(env: string, image: string): string {
  if (/^A2WAVE_IMAGE=.*$/m.test(env)) {
    return env.replace(/^A2WAVE_IMAGE=.*$/m, `A2WAVE_IMAGE=${image}`)
  }
  const separator = env.endsWith('\n') || env === '' ? '' : '\n'
  return `${env}${separator}A2WAVE_IMAGE=${image}\n`
}

/**
 * Point a legacy compose file's hardcoded `image:` at the A2WAVE_IMAGE variable.
 *
 * Installs generated before the image became an env key hardcode the ref, where
 * a new A2WAVE_IMAGE value is simply ignored — the upgrade would report success
 * while the container stayed on the old image.
 *
 * Deliberately does NOT search for "the a2wave service's image line". Locating
 * it means understanding YAML with regexes, and that is precisely what produced
 * six wrong-service rewrites before the image became a variable — each one
 * repointing a sidecar or a template while a2wave stayed stale. Instead this
 * recognises the exact single-service shape `buildComposeFile` emits, which is
 * the only file whose structure is known, and refuses everything else so the
 * operator makes the one-line edit themselves.
 *
 * Returns null when no migration is needed (already a variable); throws with the
 * exact edit to make when the file is not one this command generated.
 */
export function migrateComposeImageToVariable(compose: string): string | null {
  // "Already migrated" must mean the a2wave service's OWN image line uses the
  // variable — a whole-file substring check let a sidecar's env or a comment
  // mentioning the name skip the migration, leaving a2wave hardcoded while the
  // upgrade rewrote only .env and reported success on the old image.
  const alreadyMigrated =
    /^services:\r?\n[ \t]+a2wave:\r?\n[ \t]+image:[ \t]*\$\{A2WAVE_IMAGE[:\-}]/m
  if (alreadyMigrated.test(compose)) return null

  // The generated file declares exactly one service, `a2wave`, whose image is
  // an unquoted literal on its own line. Anything else — a second service, a
  // quoted value, an anchor block — is hand-edited and out of scope.
  const generated =
    /^services:\r?\n[ \t]+a2wave:\r?\n[ \t]+image:[ \t]*([^"'$\s#][^\s#]*)[ \t]*\r?$/m
  const match = compose.match(generated)
  // A second `image:` anywhere means another service, an anchor, or a template
  // — i.e. a file whose structure this command cannot vouch for.
  const imageCount = (compose.match(/^[ \t]*image:/gm) ?? []).length
  // Likewise a second service key: the generated file declares exactly one.
  // Walk the `services:` block explicitly and count only its direct children,
  // so nested keys like `ports:` / `volumes:` do not inflate the count.
  let inServices = false
  let serviceCount = 0
  // Depth of the service names themselves, learned from the first key inside
  // the block rather than assumed to be two spaces — `generated` accepts any
  // `[ \t]+`, so hardcoding two rejected files the rest of the check allows.
  let nameIndent: number | null = null
  for (const line of compose.split('\n')) {
    const trimmed = line.trimEnd()
    if (/^services:[ \t]*$/.test(trimmed)) {
      inServices = true
      continue
    }
    if (!inServices || trimmed === '') continue
    if (/^\S/.test(trimmed)) break // back at a top-level key: block ended
    const indent = trimmed.match(/^[ \t]*/)?.[0].length ?? 0
    if (nameIndent === null) nameIndent = indent
    if (indent === nameIndent && /:[ \t]*$/.test(trimmed)) serviceCount++
  }

  if (!match || imageCount !== 1 || serviceCount !== 1) {
    throw new Error(
      [
        'docker-compose.yml does not match the layout `a2wave setup` generates, so its image line cannot be migrated safely.',
        'Edit it by hand — change the a2wave service to read the image from .env:',
        '    image: ${A2WAVE_IMAGE:-<your current image>}',
        'then re-run the upgrade.',
      ].join('\n'),
    )
  }
  return compose.replace(generated, (line, ref: string) =>
    line.replace(`image: ${ref}`, `image: \${A2WAVE_IMAGE:-${ref}}`),
  )
}

export interface ComposeFileInput {
  image: string
  port: number
  /** Add the bundled postgres:16-alpine sidecar (EXPERIMENTAL backend). */
  withPostgres?: boolean
}

/**
 * Render a minimal docker-compose.yml for a public install.
 * Deliberately excludes internal-only settings (P4 SCM, IDaaS, provider CLI
 * home mounts) — advanced deployments should consult the docs instead.
 */
export function buildComposeFile(input: ComposeFileInput): string {
  return [
    'services:',
    '  a2wave:',
    // Variable, not a hardcoded ref: an upgrade then means writing one line in
    // .env instead of locating and rewriting this line, which required parsing
    // YAML with regexes and mis-targeted the wrong service in six distinct
    // valid-compose shapes. The generation-time ref stays as the fallback so
    // the file still works standalone.
    //
    // Must stay the FIRST key of this service: `setup --upgrade` recognizes a
    // generated file by `services:\n  a2wave:\n    image: ${A2WAVE_IMAGE...`
    // and refuses anything else as hand-edited.
    `    image: \${A2WAVE_IMAGE:-${input.image}}`,
    ...(input.withPostgres
      ? [
          // Migrations run at startup and exit(1) on failure, so without this a
          // cold start races initdb and surfaces as a migration failure.
          '    depends_on:',
          '      postgres:',
          '        condition: service_healthy',
        ]
      : []),
    '    ports:',
    // Read the host port from .env so editing A2WAVE_PORT there actually works;
    // the generation-time port is only the fallback default.
    `      - "\${A2WAVE_PORT:-${input.port}}:3502"`,
    '    env_file:',
    '      - .env',
    '    environment:',
    '      - NODE_ENV=production',
    '      - PORT=3502',
    // From .env, like the image: switching backends must be a one-line .env
    // edit. A hardcoded value here would override env_file and make a
    // DATABASE_URL added to .env silently inert.
    '      - DATABASE_URL=${DATABASE_URL:-/app/data/a2wave.db}',
    '      - A2WAVE_SKILLS_STORAGE=/app/data/skills',
    '      - SCM_STORAGE_ROOT=${SCM_STORAGE_ROOT:-/data/workspace}',
    '      - SCM_WORKSPACES_ALLOWED_ROOTS=${SCM_WORKSPACES_ALLOWED_ROOTS:-/data/workspace/workspaces}',
    '    volumes:',
    '      - a2wave-data:/app/data',
    '      - a2wave-workspace:/data/workspace',
    // Provider CLIs (Cursor / Codex / Claude Code / ...) persist localSession
    // state under the service HOME; without this volume every container
    // rebuild wipes those logins.
    '      - a2wave-cli-home:/home/appuser',
    '    restart: unless-stopped',
    ...(input.withPostgres
      ? [
          '',
          '  # PostgreSQL backend — EXPERIMENTAL: no production soak time, and no',
          '  # SQLite -> PostgreSQL data migration path.',
          '  postgres:',
          '    image: postgres:16-alpine',
          '    environment:',
          '      - POSTGRES_USER=a2wave',
          // The password lives in .env only (0600); an inline literal here
          // would duplicate it into a world-readable file.
          '      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?set in .env}',
          '      - POSTGRES_DB=a2wave',
          '    volumes:',
          '      - a2wave-postgres:/var/lib/postgresql/data',
          // Not published on the host: the API reaches it over the compose
          // network, and binding 5432 would expose the database to anything
          // that can reach the machine.
          '    expose:',
          '      - "5432"',
          '    healthcheck:',
          '      test: ["CMD-SHELL", "pg_isready -U a2wave -d a2wave"]',
          '      interval: 10s',
          '      timeout: 5s',
          '      retries: 5',
          '    restart: unless-stopped',
        ]
      : []),
    '',
    'volumes:',
    '  a2wave-data:',
    '  a2wave-workspace:',
    '  a2wave-cli-home:',
    ...(input.withPostgres ? ['  a2wave-postgres:'] : []),
    '',
  ].join('\n')
}
