#!/usr/bin/env node
/**
 * Generate `src/generated/schemas.json` from the @a2wave/shared zod schemas.
 *
 * WHY a build-time artifact rather than a runtime import: the published package
 * declares exactly `citty` + `yaml`. Importing @a2wave/shared at runtime would
 * inline zod into the single-file CJS bundle and couple every CLI release to a
 * shared version. A JSON snapshot costs tens of KB and no dependency.
 *
 * The snapshot is what makes the hand-written mirrors in src/lib/agent-yaml.ts
 * un-driftable: `src/lib/__tests__/agent-yaml.test.ts` asserts each mirror
 * equals its generated counterpart, and `src/__tests__/generated-schemas.test.ts`
 * asserts this file is itself current. A shared-side enum change therefore
 * fails CI here instead of silently rejecting a YAML the API would accept.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const OUT_DIR = join(here, '..', 'src', 'generated')
const OUT_FILE = join(OUT_DIR, 'schemas.json')

async function loadShared() {
  try {
    return await import('@a2wave/shared')
  } catch (err) {
    // A raw ERR_MODULE_NOT_FOUND here means the workspace package has no build
    // output yet, which is a one-command fix — say so rather than making the
    // reader decode a resolver stack.
    throw new Error(
      `Cannot load @a2wave/shared. Build it first:\n  pnpm --filter @a2wave/shared build\n\nUnderlying error: ${err?.message ?? err}`,
    )
  }
}

/**
 * Enum members only. `zodToJsonSchema` would give the same list wrapped in a
 * JSON-Schema envelope, but these feed CLI-side unions and `enum` lists in the
 * function-calling spec, where a bare array is what every consumer wants.
 */
function enumValues(schema) {
  return [...schema.options]
}

const shared = await loadShared()
const { zodToJsonSchema } = await import('zod-to-json-schema')

const toJson = (schema, name) =>
  zodToJsonSchema(schema, { target: 'jsonSchema7', $refStrategy: 'none', name })

const generated = {
  // Regenerated by `pnpm gen:schemas`; committed so dev/test need no build step.
  $comment: 'GENERATED by apps/cli/scripts/gen-schemas.mjs — do not edit by hand.',
  enums: {
    publishChannel: enumValues(shared.publishChannelEnum),
    publishAuthType: enumValues(shared.publishAuthTypeEnum),
    agentType: enumValues(shared.agentTypeEnum),
    agentStatus: enumValues(shared.agentStatusEnum),
    publishStatus: enumValues(shared.publishStatusEnum),
    workspaceType: enumValues(shared.workspaceTypeEnum),
    authMode: enumValues(shared.authModeEnum),
    runStatus: enumValues(shared.runStatusEnum),
    mcpServerType: enumValues(shared.mcpServerTypeEnum),
  },
  objects: {
    feishuConfig: toJson(shared.feishuConfigSchema, 'feishuConfig'),
    artifactPolicy: toJson(shared.artifactPolicySchema, 'artifactPolicy'),
    a2aRouteTarget: toJson(shared.a2aRouteTargetSchema, 'a2aRouteTarget'),
    a2aSkill: toJson(shared.a2aSkillSchema, 'a2aSkill'),
    scheduleConfig: toJson(shared.scheduleConfigSchema, 'scheduleConfig'),
  },
}

mkdirSync(OUT_DIR, { recursive: true })
writeFileSync(OUT_FILE, `${JSON.stringify(generated, null, 2)}\n`)
process.stdout.write(`wrote ${OUT_FILE}\n`)
