#!/usr/bin/env node
/**
 * Generate the agent guide: `src/generated/agent-guide.ts` (bundled into the
 * binary so `a2wave docs` works everywhere) and `dist/agent-guide.md` (readable
 * without running the CLI, and inside the published `files` list via `dist`).
 *
 * The prose lives here; only the COMMAND MAP's leaf list comes from the citty
 * tree, so the map cannot describe commands the CLI no longer has. A gate test
 * (`src/__tests__/agent-guide.test.ts`) re-derives the list and fails on drift.
 */
import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const cliRoot = join(here, '..')

const { buildGuideMarkdown } = await import(join(cliRoot, 'scripts', 'guide-content.mjs'))

/**
 * Ask the CLI itself for its command paths rather than rebuilding the tree.
 *
 * `src/index.ts` dispatches on import, so it cannot be imported for its tree —
 * but it can be RUN, and `schema --json` with no argument is exactly the index
 * this needs. One tree, one answer, no second description to drift.
 */
function collectLeafPaths() {
  const out = execFileSync('npx', ['tsx', join(cliRoot, 'src', 'index.ts'), 'schema', '--json'], {
    cwd: cliRoot,
    encoding: 'utf-8',
    // No instance is contacted, but a stale URL in the environment would still
    // be inherited; `schema` never dials out, so this only keeps the run hermetic.
    env: { ...process.env, A2WAVE_URL: '' },
  })
  return JSON.parse(out).commands
}

const markdown = buildGuideMarkdown(collectLeafPaths())

mkdirSync(join(cliRoot, 'src', 'generated'), { recursive: true })
writeFileSync(
  join(cliRoot, 'src', 'generated', 'agent-guide.ts'),
  `// GENERATED by apps/cli/scripts/gen-guide.mjs — do not edit by hand.\nexport const AGENT_GUIDE = ${JSON.stringify(markdown)}\n`,
)

mkdirSync(join(cliRoot, 'dist'), { recursive: true })
writeFileSync(join(cliRoot, 'dist', 'agent-guide.md'), markdown)

process.stdout.write(`wrote agent-guide (${markdown.split('\n').length} lines)\n`)
