/**
 * The mirrors in agent-yaml.ts must equal what @a2wave/shared actually declares.
 *
 * They used to be hand-written unions, and they drifted: `publish.channels`
 * listed five channels while the platform had ten, so `agents apply` on a YAML
 * declaring `channels: [slack]` was rejected CLI-side by a value the API would
 * have accepted. Widening the union by hand fixes today's list and nothing
 * else — the next channel added to shared reproduces the bug.
 *
 * So the mirrors are now runtime constants compared against the build-time
 * snapshot in src/generated/schemas.json (regenerated by `pnpm gen:schemas`,
 * kept current by src/__tests__/generated-schemas.test.ts). A shared-side change
 * fails here instead of shipping.
 */
import { describe, expect, it } from 'vitest'
import generated from '../../generated/schemas.json' with { type: 'json' }
import {
  A2A_CONNECTION_MODES,
  A2A_PROTOCOL_VERSIONS,
  A2A_ROUTE_TARGET_TYPES,
  ARTIFACT_AUTO_SHARE,
  ARTIFACT_SHARE_ACCESS_LEVELS,
  FEISHU_CONFIG_KEYS,
  PUBLISH_AUTH_TYPES,
  PUBLISH_CHANNELS,
} from '../agent-yaml.js'

/** Unwrap whichever envelope zod-to-json-schema produced for a named object. */
function properties(name: 'feishuConfig' | 'artifactPolicy'): Record<string, unknown> {
  const doc = generated.objects[name] as Record<string, unknown>
  const definitions = doc.definitions as Record<string, { properties?: Record<string, unknown> }>
  const props = definitions?.[name]?.properties ?? (doc.properties as Record<string, unknown>)
  return props ?? {}
}

describe('agent-yaml mirrors match the generated shared schemas', () => {
  it('PUBLISH_CHANNELS equals publishChannelEnum', () => {
    expect(PUBLISH_CHANNELS).toEqual(generated.enums.publishChannel)
  })

  it('PUBLISH_AUTH_TYPES equals publishAuthTypeEnum', () => {
    expect(PUBLISH_AUTH_TYPES).toEqual(generated.enums.publishAuthType)
  })

  it('artifactPolicy mirrors the shared enums and key set', () => {
    const props = properties('artifactPolicy')
    expect(Object.keys(props).sort()).toEqual(
      ['autoShare', 'shareAccessLevel', 'shareExpiryDays'].sort(),
    )
    expect(ARTIFACT_AUTO_SHARE).toEqual((props.autoShare as { enum: string[] }).enum)
    expect(ARTIFACT_SHARE_ACCESS_LEVELS).toEqual(
      (props.shareAccessLevel as { enum: string[] }).enum,
    )
  })

  it('a2aRouteTarget mirrors the shared discriminated union', () => {
    const doc = generated.objects.a2aRouteTarget as Record<string, unknown>
    const definitions = doc.definitions as
      | Record<string, { anyOf?: Array<Record<string, unknown>> }>
      | undefined
    const variants = (definitions?.a2aRouteTarget?.anyOf ??
      (doc.anyOf as Array<Record<string, unknown>>)) as Array<{
      properties: Record<string, { const?: string; enum?: string[] }>
    }>

    const types = variants.map((v) => v.properties.type.const ?? v.properties.type.enum?.[0])
    expect(A2A_ROUTE_TARGET_TYPES).toEqual(types)

    const remote = variants.find((v) => v.properties.connectionMode)
    expect(A2A_CONNECTION_MODES).toEqual(remote?.properties.connectionMode.enum)
    expect(A2A_PROTOCOL_VERSIONS).toEqual(remote?.properties.protocolVersion.enum)
  })

  it('FEISHU_CONFIG_KEYS covers every field of feishuConfigSchema', () => {
    // Key-set equality rather than per-field types: the CLI only needs to know
    // which keys are legal to pass through, and a ~23-field type mirror is what
    // rots. The runtime list is what `agents apply` validates against.
    expect([...FEISHU_CONFIG_KEYS].sort()).toEqual(Object.keys(properties('feishuConfig')).sort())
  })
})
